---

- name: install curl
  apt:
    name: curl
    state: present

- name: install helm
  shell: if [ -z `which helm` ]; then curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | sh -; else echo "helm already installed"; fi

- name: create charts directory
  file:
    path: "{{ home_dir }}/{{ config_dir }}/charts"
    state: directory

- name: install git
  apt:
    name: git
    state: present
