---
- name: Create cert-manager namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    kind: Namespace
    definition:
      metadata:
        labels:
          name: "cert-manager"
        name: "filter"

- name: Add jetstack repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install cert-manager
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    release_namespace: cert-manager
    chart_ref: jetstack/cert-manager
    release_name: cert-manager
    values:
      installCRDs: True
