---

- name: install curl
  apt:
    name: curl
    state: present

- name: install netplan
  apt:
    name: netplan.io
    state: present

- name: install k3s
  shell: if [ -z `which kubectl` ]; then curl -sfL https://get.k3s.io | sh -; else echo "k3s already installed"; fi

- name: create mount directory
  file:
    path: "{{ home_dir }}/{{ config_dir }}/volumes"
    state: directory

- name: create db mount directory
  file:
    path: "{{ home_dir }}/{{ config_dir }}/volumes/db"
    state: directory

- name: create phrases mount directory
  file:
    path: "{{ home_dir }}/{{ config_dir }}/volumes/phrases"
    state: directory
