---
- name: Check if /boot/cmdline.txt exists
  stat:
    path: /boot/cmdline.txt
  register: cmdline_txt

- set_fact:
    cmdline_txt_path: /boot/cmdline.txt

- include_tasks: cmdline.yml
  vars:
    key: cgroup_enable
    value: memory
    update: false
  when: cmdline_txt.stat.exists == True

- include_tasks: cmdline.yml
  vars:
    key: cgroup_memory
    value: 1
    update: true
  when: cmdline_txt.stat.exists == True